- name: Installing mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Starting and enabling mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
  
  